name: Deploy File

on:
  push:
    branches:
      - main

jobs:
  deploy_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4        
        with:          
          node-version: '24'
      - name: install dependencies
        run: npm ci
      - name: Check style        
        run: npm run eslint
      - name: build appJs
        run: npm run build
        env:
          SUB_URL: ${{ secrets.SUB_URL }}
          SUB_KEY: ${{ secrets.SUB_KEY }}
